name: mbark_iptv
description: A Flutter IPTV client.

publish_to: 'none'

version: 1.0.7+8

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  awesome_snackbar_content: ^0.1.8
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  filling_slider: ^0.0.3
  flutter_bloc: ^8.1.6
  flutter_rating_bar: ^4.0.1
  flutter_vlc_player: ^7.4.4
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^7.0.0
  google_mobile_ads: ^5.1.0
  intl: ^0.20.2
  loading_animation_widget: ^1.2.1
  pod_player: ^0.2.2
  readmore: ^3.0.0
  responsive_sizer: ^3.3.1
  screen_brightness_util: ^0.0.3
  url_launcher: ^6.3.0
  volume_controller: ^2.0.8
  wakelock_plus: ^1.2.11

dependency_overrides:
  win32: 5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  min_sdk_android: 21
